###

# @name register
POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "foo",
  "name": "Nathan"
}

###

# @name logIn
POST http://localhost:3000/logIn
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "foo"
}

###

# @name logOut
POST http://localhost:3000/logOut
Content-Type: application/json

{
  "refreshToken": "{{logIn.response.body.refreshToken}}"
}

###

# @name refreshSession
POST http://localhost:3000/refresh
Content-Type: application/json

{
  "refreshToken": "{{logIn.response.body.refreshToken}}"
}

###

# @name getUser
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

###

# @name updateUser
POST http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

{
  "name": "Nathan Betts"
}

###

# @name updatePassword
POST http://localhost:3000/password
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

{
  "currentPassword": "foo",
  "newPassword": "bar"
}
