###

# @name logIn
POST http://localhost:3000/session
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "foo"
}

###

# @name logOut
DELETE http://localhost:3000/session
Content-Type: application/json

{
  "refreshToken": "{{logIn.response.body.refreshToken}}"
}

###

# @name refreshSession
PUT http://localhost:3000/session
Content-Type: application/json

{
  "refreshToken": "{{logIn.response.body.refreshToken}}"
}

###

# @name register
POST http://localhost:3000/user
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "foo",
  "name": "Nathan"
}

###

# @name getUser
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

###

# @name updateUser
PUT http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

{
  "name": "Nathan Betts"
}

###

# @name updatePassword
PUT http://localhost:3000/user/password
Content-Type: application/json
Authorization: Bearer {{logIn.response.body.accessToken}}

{
  "currentPassword": "foo",
  "newPassword": "bar"
}
